@startuml
!include <archimate/Archimate>
!include ../publish/plantuml-style.puml
title Transacties binnen de lokalisatiefunctie

skinparam nodesep 20
skinparam ranksep 35

rectangle "Lokalisatieclients" as GRP_C {
  Application_Component(reg, "Localization\nRegistration Client")
  Application_Component(search, "Localization\nSearch Client")
}

rectangle "PRS" as GRP_P {
  Application_Interface(if_prs, "PRS API")
  Application_Service(svc_pseudo, "Evaluate blinded input\n(GF-PSD-1)")
}

rectangle "NVI" as GRP_N {
  Application_Component(nvi, "NVI")
  Application_Interface(if_nvi, "NVI API")
  Application_Service(svc_reg, "Register Patient\n(GF-LOC-1)")
  Application_Service(svc_del, "Delete Patient\n(GF-LOC-2)")
  Application_Service(svc_own, "Retrieve Registrations\n(GF-LOC-3)")
  Application_Service(svc_loc, "Search Localization\n(GF-LOC-4)")
}

rectangle "Bronhoudende zorgaanbieder" as GRP_B {
  Application_Interface(if_bron, "Zorgaanbieder-\nendpoint (FHIR)")
  Application_Service(svc_dec, "Authorization Decision\n(GF-LOC-5)")
  Application_Service(svc_get, "(Meta)gegevens\nophalen")
}

Rel_Composition(if_prs, svc_pseudo, "")
Rel_Composition(if_nvi, svc_reg, "")
Rel_Composition(if_nvi, svc_del, "")
Rel_Composition(if_nvi, svc_own, "")
Rel_Composition(if_nvi, svc_loc, "")
Rel_Composition(if_bron, svc_dec, "")
Rel_Composition(if_bron, svc_get, "")

Rel_Serving(svc_pseudo, reg, "")
Rel_Serving(svc_pseudo, search, "")
Rel_Serving(svc_reg, reg, "")
Rel_Serving(svc_del, reg, "")
Rel_Serving(svc_own, reg, "")
Rel_Serving(svc_loc, search, "")
Rel_Serving(svc_dec, nvi, "")
Rel_Serving(svc_get, search, "")

Lay_D(GRP_C, GRP_P)
Lay_D(GRP_P, GRP_N)
Lay_D(GRP_N, GRP_B)
@enduml
