@startuml
title UC-NVI-02. Registratie van een lokalisatierecord

actor "Eindgebruiker" as ZV
participant "XIS (component Lokalisatie-client)" as XIS
participant "PRS" as PRS
participant "NVI" as NVI

ZV -> XIS: legt gegevens vast\n(bijv. onderzoek afgerond)
activate XIS

note over XIS
  XIS (of Eindgebruiker) stelt vast dat er toestemming voor
  de registratie van het lokalisatie-record in de NVI is.
  De NVI controleert dit niet zelf.
end note

XIS -> PRS: vraag pseudoniem\n(BSN)
activate PRS
PRS --> XIS: pseudoniem
deactivate PRS

XIS -> NVI: registreer (pseudoniem, URA,\nbronsysteem)
activate NVI

alt nog geen registratie
  NVI --> XIS: registratie vastgelegd
else registratie bestaat al
  NVI --> XIS: registratie niet vastgelegd \n(geen duplicaat)
end
deactivate NVI
deactivate XIS

note over NVI
  Het lokalisatie-record is nu geregistreerd in de NVI.
  Opvragen van lokalisatie-records (UC-NVI-03) is nu mogelijk.
end note
@enduml
