@startuml
title Componenten van de generieke functie Lokalisatie

package "Bij de Bevragende Zorgaanbieder" {
  component "XIS" as xis
  component "Lokalisatie-\nclient (H13)" as client

}

package "Landelijke voorzieningen" {
  component "Pseudoniemen-\nregistratie-\nservice (H12)" as prs
  component "Nationale\nVerwijsindex\n(H11)" as nvi
}

package "Gedelegeerd aan een\nandere generieke functie" {
  component "GF\nAdressering" as adressering
}

package "Bij de Datahoudende Zorgaanbieder" {
  component "XIS" as bronxis
  component "Lokalisatie-\nAddressering-\nserver (H14)" as LAs
  interface "Zorgaanbieder-\nendpoint\n(FHIR-URL)" as endpoint
}

xis *-- client
bronxis *-- endpoint

client ..> prs : vraagt\npseudoniem
client ..> nvi : registreert,\nlokaliseert
xis ..> adressering : zoekt\nendpoints op
endpoint ..> xis : levert\n(meta)gegevens
nvi ..> LAs : vraagt akkoord voor delen \nlokalisatie-record met \nBevragende Zorgaanbieder
xis ..[hidden]up..> endpoint

@enduml
