@startuml
title UC-NVI-05. Raadplegen van de eigen registraties

participant "XIS (component Lokalisatie-client)" as XIS
participant "PRS" as PRS
participant "NVI" as NVI

alt voor één burger
  XIS -> PRS: vraag pseudoniem\n(BSN)
  activate PRS
  PRS --> XIS: pseudoniem
  deactivate PRS
  XIS -> NVI: vraag eigen registraties\n(pseudoniem, systeem-identifier)
else voor alle burgers
  XIS -> NVI: vraag alle eigen registraties\n(systeem-identifier)
end

activate NVI
note over NVI
  De lijst is beperkt tot de registraties
  van het XIS met systeem-identifier. 
  Pseudoniem zijn geen onderdeel van response.
end note
NVI --> XIS: de eigen registraties
deactivate NVI

note over XIS
  Bij een afwijking: corrigeren via
  UC-NVI-04 (verwijderen) en UC-NVI-02
  (opnieuw registreren).
end note
@enduml
