@startuml
|Zorgverlener|
start
:1. Voert een onderzoek uit en \nregistreert in XIS;
|Zorginformatiesysteem \n(component Lokalisatie-client)|
:2a. Vraagt pseudoniem aan;
|PRS|
:2b. Levert pseudonimiem;
|Zorginformatiesysteem \n(component Lokalisatie-client)|
:3. Registreert lokalisatie-record;
|NVI|
:4. Het lokalisatie-record is nu opvraagbaar \nvoor andere zorgverleners.;
stop
@enduml