@startuml
|Zorgverlener (Eindgebruiker)|
start
:1. Opent het patiëntdossier in het XIS;
:2. Opent scherm "patient-samenvatting";
|Zorginformatiesysteem \n(component Lokalisatie-client)|
:3a. Vraagt pseudoniem aan;
|PRS|
:3b. Levert pseudonimiem;
|Zorginformatiesysteem \n(component Lokalisatie-client)|
:4. Vraagt lokalisatie-records op;
|NVI|
:5. Levert lokalisatie-records op; 
|Zorginformatiesysteem \n(component Lokalisatie-client)|
:6a. Levert lijst van zorgaanbieders op;
|Zorginformatiesysteem \n(overige componenten)|
:6b. haalt data bij zorgaanbieders op;
:7. Toont patiënt-samenvatting samengesteld \nuit data van verschillende zorgaanbieders.;
|Zorgverlener (Eindgebruiker)|
stop
@enduml